### ISSUE TITLE
Variable substitution using {{{<variable>}}} in 'runcmd' section of cloudinit in parts/*.t causes acs-engine crash

### ISSUE THREAD

**Issue by jmspring** [Azure/acs-engine#1109]
**Is this a request for help?**: No
**Is this an ISSUE or FEATURE REQUEST?** Issue
**What version of acs-engine?**: 0.4.0

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**: DC/OS (but shouldn't matter)

**What happened**: Upon attempting to generate azuredeploy.json, acs-engine crashes

**What you expected to happen**: Not to crash

**How to reproduce it** (as minimally and precisely as possible):

Add the following to the end of the `runcmd` block in `parts/dcoscustomdata190.t`:

```
- - adduser
  - {{{adminUsername}}}
  - docker
```

Build acs-engine and attempt to create the `azuredeploy.json` and related files.  acs-engine will crash.

**Comment by jmspring** [comment]
Partial stack trace:

```
acs-engine generate --classic-mode --output-directory ./output ./dcos-gpu-general-managed-disk.json 
INFO[0000] Generating assets...                         
FATA[0000] error generating template ./dcos-gpu-general-managed-disk.json: BUG: yaml: invalid map key: map[interface {}]interface {}{"adminUsername":interface {}(nil)} - goroutine 1 [running]:
runtime/debug.Stack(0xc4204604c8, 0x99f140, 0xc4201e0b90)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/Azure/acs-engine/pkg/acsengine.(*TemplateGenerator).GenerateTemplate.func1(0xc420461b80, 0xc420461b58, 0xc420461b68)
	/home/jims/code/src/github.com/Azure/acs-engine/pkg/acsengine/engine.go:247 +0x6e
panic(0x99f140, 0xc4201e0b90)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
text/template.errRecover(0xc420461958)
	/usr/local/go/src/text/template/exec.go:146 +0x62
panic(0x99f140, 0xc4201e0b90)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/Azure/acs-engine/pkg/acsengine.getSingleLineDCOSCustomData(0xa61f07, 0x4, 0xa623d4, 0x5, 0x1, 0xc4203bbb00, 0x8cc, 0xc4203ec390, 0x22, 0x0, ...)
	/home/jims/code/src/github.com/Azure/acs-engine/pkg/acsengine/engine.go:1315 +0x819
github.com/Azure/acs-engine/pkg/acsengine.(*TemplateGenerator).getTemplateFuncMap.func24(0xc4200b28c0, 0x0, 0x0)
	/home/jims/code/src/github.com/Azure/acs-engine/pkg/acsengine/engine.go:647 +0xd8
reflect.Value.call(0x9ad7e0, 0xc4201e10f0, 0x13, 0xa61ef7, 0x4, 0xc42000db20, 0x1, 0x1, 0x1, 0x1, ...)
	/usr/local/go/src/reflect/value.go:434 +0x91f
```
