### ISSUE TITLE
dcos cluster deployed fail in Azure China

### ISSUE THREAD

**Issue by kingliantop** [Azure/acs-engine#112]
Hi guys,
I used acs-engine to generate acs template and deploy to China, while at the last step, it showed the following information:

info:    Resource 'dcos-agentpublic-nsg-31045692' of type 'Microsoft.Network/networkSecurityGroups' provisioning status is Succeeded
info:    Resource 'dcos-agentprivate-nsg-31045692' of type 'Microsoft.Network/networkSecurityGroups' provisioning status is Succeeded
error:   connect EAGAIN 42.159.198.85:443 - Local (0.0.0.0:17141)
error:   Error information has been recorded to /home/steven/.azure/azure.err
error:   group deployment create command failed

/home/steven/.azure/azure.err file details:

2016-11-19T16:13:31.024Z:
{ [Error: connect EAGAIN 42.159.198.85:443 - Local (0.0.0.0:17141)]
  stack: [Getter/Setter],
  code: 'EAGAIN',
  errno: 'EAGAIN',
  syscall: 'connect',
  address: '42.159.198.85',
  port: 443,
  __frame:
   { name: '__1',
     line: 79,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js',
     prev:
      { name: '__1',
        line: 52,
        file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js',
        prev: undefined,
        calls: 2,
        active: false,
        offset: 26,
        col: 24 },
     calls: 96,
     active: false,
     offset: 2,
     col: 44 },
  rawStack: [Getter] }
Error: connect EAGAIN 42.159.198.85:443 - Local (0.0.0.0:17141)
  <<< async stack >>>
  at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js:81:45)
  at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js:78:25)
  <<< raw stack >>>
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at connect (net.js:865:16)

Could you please share any ideas to help on that? Thanks a lot!

**Comment by kingliantop** [comment]
It seems the default mirror issues, how can I download everything from https://dcosio.azureedge.net/dcos/testing? It seems that I can't access that directly. I want to make a mirror in China. Thanks a lot!

**Comment by kingliantop** [comment]
Deployed successfully using my mirror, open another case to see how we can using customized URL besides manually change that.
