### ISSUE TITLE
Allow scaling a cluster with custom VM name prefix

### ISSUE THREAD

**Issue by 0x7f** [Azure/acs-engine#2295]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):

FEATURE REQUEST mostly, but a bit of an ISSUE as well ;)

**What version of acs-engine?**:

0.12.5

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 1.8.7

**What happened**:

We use acs-engine for creating k8s clusters in a fairly large infrastructure. There are two requirements: a) the resources must comply with an existing naming scheme and b) the nodes must join Active Directoy.

The first requirement ist not super strict, but due to the second one, the nodes names must not be longer than 15 chars due to NetBIOS and DNS restrictions (see [Microsoft Documentation](https://support.microsoft.com/en-us/help/909264/naming-conventions-in-active-directory-for-computers-domains-sites-and)). So we use acs-engine to generate the arm templates and then modify the `agentpoolVMNamePrefix` in the generated `azuredeploy.json` to e.g. `uniqprefix-`. So far this works great. The resource comply to our naming scheme and clusters work very well.

When now scaling the cluster by calling `acs-engine scale ...`, I get the following error:
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/Azure/acs-engine/cmd.(*scaleCmd).run(0xc4204a3380, 0xc42069b680, 0xc420164780, 0x0, 0xc, 0x0, 0x0)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/cmd/scale.go:213 +0x258b
github.com/Azure/acs-engine/cmd.newScaleCmd.func1(0xc42069b680, 0xc420164780, 0x0, 0xc, 0x0, 0x0)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/cmd/scale.go:66 +0x52
github.com/Azure/acs-engine/vendor/github.com/spf13/cobra.(*Command).execute(0xc42069b680, 0xc4201640c0, 0xc, 0xc, 0xc42069b680, 0xc4201640c0)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/command.go:647 +0x3f1
github.com/Azure/acs-engine/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42069a480, 0xc42069b680, 0xc42069b440, 0xc42069afc0)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/command.go:726 +0x2fe
github.com/Azure/acs-engine/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42069a480, 0x0, 0x0)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/main.go:9 +0x27
```

It is crashing [here](https://github.com/Azure/acs-engine/blob/v0.12.5/cmd/scale.go#L213) because the list of indexes is empty. This is because it is calling [K8sLinuxVMNameParts](https://github.com/Azure/acs-engine/blob/v0.12.5/pkg/armhelpers/utils/util.go#L71-L85) which requires the nodes names to be of the [default naming convention](https://github.com/Azure/acs-engine/blob/v0.12.5/pkg/armhelpers/utils/util.go#L16-L20). Which is ok in a way - no one should mess around with the internals of acs-engine. But I can't stick to the default name unfortunately, because it is too long to join Active Directory. 

So when having a look what the code is trying to achieve in the first place: finding all node indexes (last part of the name) to generate the names for the new nodes. This can be achieved with a more relaxed naming convention as well where imho: just looking for the last dash and interpreting the part behind as the index (`uniqprefix-0` in my case would be index `0`).

**What you expected to happen**:

`acs-engine scale` should use `/.*-([0-9]+)/` to find the node indexes or similar solutions to allow scaling clusters with custom names.

**How to reproduce it** (as minimally and precisely as possible):

Generate cluster, modify `agentpoolVMNamePrefix` in `azuredeploy.json` to sth non-standard, deploy the arm template and then try to scale the cluster.

**Anything else we need to know**:

You are doing a great job :)

**Comment by 0x7f** [comment]
Btw, was already searching for similar issue, but only found this PR https://github.com/Azure/acs-engine/pull/2000 which is only somewhat related.
