### ISSUE TITLE
Windows VM VMSS issues with CNI

### ISSUE THREAD

**Issue by beaudryj** [Azure/acs-engine#2911]
**Is this a request for help?**: Help
---

**What version of acs-engine?**:  master - commit 28eb1d106e17281eab2753464a60ceafa1b85ea1

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** 
k8s - 1.10.2

**What happened**:
For the most part the Windows VMSS seem to work, the kublet comes up it starts, it even registers with the master as healthy, however it seems as though there is something wrong with the CNI and how it gets installed or configured. I have tried nuking all of the nodes and bringing up new with the scale set to try to somehow redeploy, but the kubelet does not seem happy with the CNI nor am I able to get any windows containers to standup on the nodes. I am using whatever the default network plugin is I do not modify that at all so this is all standard CNI for ACS-Engine deploy on windows. 

**What you expected to happen**:

What I expected to happen was to start my pod and get a Windows SQL container running (running sql:1709)

**How to reproduce it** (as minimally and precisely as possible):

```
{
    "apiVersion": "vlabs",
    "properties": {
      "orchestratorProfile": {
        "orchestratorType": "Kubernetes",
        "orchestratorRelease": "1.10",
        "kubernetesConfig": {
          "enableRbac": true,
          "apiServerConfig" : {
            "--feature-gates": "HyperVContainer=true"
          },
          "kubeletConfig" : {
            "--feature-gates": "HyperVContainer=true"
           }
        }
      },
      "aadProfile": {
        "serverAppID":  "",
        "clientAppID":  "",
        "tenantID":  "",
        "adminGroupID":  ""
      },
      "masterProfile": {
        "count": 1,
        "dnsPrefix": "ebk8s",
        "vmSize": "Standard_F2s_v2"
      },
      "agentPoolProfiles": [
        {
          "name": "linuxpool1",
          "count": 2,
          "vmSize": "Standard_F4s_v2",
          "availabilityProfile": "VirtualMachineScaleSets",
          "storageProfile": "ManagedDisks",
          "OSDiskSizeGB": 256
        },
        {
          "name": "windowspool2",
          "count": 2,
          "vmSize": "Standard_F4s_v2",
          "availabilityProfile": "VirtualMachineScaleSets",
          "storageProfile": "ManagedDisks",
          "OSDiskSizeGB": 256,
          "osType": "Windows"
        }
      ],
      "windowsProfile": {
        "adminUsername": "",
        "adminPassword": ""      },
      "linuxProfile": {
        "adminUsername": "",
        "ssh": {
          "publicKeys": [
            {
              "keyData":  ""
            }
          ]
        }
      },
      "servicePrincipalProfile": {
        "clientId":  "",
        "secret":  ""
      }
    }
  }
```

**Anything else we need to know**:
some logs from my kubelet to help
```
goroutine 1 [running]:
visualstudio.com/containernetworking/cni/cni.(*NetworkConfig).GetNetworkInfo(0xc042046140, 0x29)
	/home/madhanm/repo/gopath/src/visualstudio.com/containernetworking/cni/cni/cni.go:175 +0x70e
visualstudio.com/containernetworking/cni/cni/network.(*netPlugin).Add(0xc042002540, 0xc042080070, 0x1, 0x0)
	/home/madhanm/repo/gopath/src/visualstudio.com/containernetworking/cni/cni/network/network.go:108 +0x35b
visualstudio.com/containernetworking/cni/cni.(PluginApi).Add-fm(0xc042080070, 0xc04201fbc8, 0x5)
	/home/madhanm/repo/gopath/src/visualstudio.com/containernetworking/cni/cni/plugin.go:49 +0x40
github.com/containernetworking/cni/pkg/skel.(*dispatcher).checkVersionAndCall(0xc042036280, 0xc042080070, 0x6311a0, 0xc0420b01e0, 0xc04205fe78, 0x0, 0x41055f)
	/home/madhanm/repo/gopath/src/github.com/containernetworking/cni/pkg/skel/skel.go:162 +0x1a6
github.com/containernetworking/cni/pkg/skel.(*dispatcher).pluginMain(0xc042036280, 0xc04205fe78, 0xc04205fe90, 0x6311a0, 0xc0420b01e0, 0xc0420b01e0)
	/home/madhanm/repo/gopath/src/github.com/containernetworking/cni/pkg/skel/skel.go:173 +0x2a9
github.com/containernetworking/cni/pkg/skel.PluginMainWithError(0xc04205fe78, 0xc04205fe90, 0x6311a0, 0xc0420b01e0, 0xc0420b01e0)
	/home/madhanm/repo/gopath/src/github.com/containernetworking/cni/pkg/skel/skel.go:210 +0xf4
visualstudio.com/containernetworking/cni/cni.(*Plugin).Execute(0xc042004038, 0x631520, 0xc042002540, 0x0, 0xc042071c20)
	/home/madhanm/repo/gopath/src/visualstudio.com/containernetworking/cni/cni/plugin.go:49 +0xf9
main.main()
	/home/madhanm/repo/gopath/src/visualstudio.com/containernetworking/cni/cni/network/plugin/main.go:43 +0x35c
E0510 15:54:30.397865    4684 cni.go:259] Error adding network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
E0510 15:54:30.397865    4684 cni.go:227] Error while adding to cni network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
E0510 15:54:30.744409    4684 remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "msftdb_default" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
E0510 15:54:30.744409    4684 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "msftdb_default(cdf7e940-5466-11e8-b6dc-000d3a066105)" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "msftdb_default" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
E0510 15:54:30.744409    4684 kuberuntime_manager.go:646] createPodSandbox for pod "msftdb_default(cdf7e940-5466-11e8-b6dc-000d3a066105)" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "msftdb_default" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
E0510 15:54:30.745431    4684 pod_workers.go:186] Error syncing pod cdf7e940-5466-11e8-b6dc-000d3a066105 ("msftdb_default(cdf7e940-5466-11e8-b6dc-000d3a066105)"), skipping: failed to "CreatePodSandbox" for "msftdb_default(cdf7e940-5466-11e8-b6dc-000d3a066105)" with CreatePodSandboxError: "CreatePodSandbox for pod \"msftdb_default(cdf7e940-5466-11e8-b6dc-000d3a066105)\" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod \"msftdb_default\" network: netplugin failed but error parsing its diagnostic message \"\": unexpected end of JSON input"
I0510 15:54:31.341582    4684 kubelet.go:1901] SyncLoop (PLEG): "msftdb_default(cdf7e940-5466-11e8-b6dc-000d3a066105)", event: &pleg.PodLifecycleEvent{ID:"cdf7e940-5466-11e8-b6dc-000d3a066105", Type:"ContainerDied", Data:"5c100367f279f32adb2c862099dadc2a9c27ebae5f877940f3bde631cd158b15"}
W0510 15:54:31.341582    4684 pod_container_deletor.go:77] Container "5c100367f279f32adb2c862099dadc2a9c27ebae5f877940f3bde631cd158b15" not found in pod's containers
I0510 15:54:31.642578    4684 kuberuntime_manager.go:403] No ready sandbox for pod "msftdb_default(cdf7e940-5466-11e8-b6dc-000d3a066105)" can be found. Need to start a new one
E0510 15:54:32.460642    4684 docker_sandbox.go:657] ResolvConfPath is empty.
I0510 15:54:32.482637    4684 kubelet.go:1901] SyncLoop (PLEG): "msftdb_default(cdf7e940-5466-11e8-b6dc-000d3a066105)", event: &pleg.PodLifecycleEvent{ID:"cdf7e940-5466-11e8-b6dc-000d3a066105", Type:"ContainerStarted", Data:"8b0938b6c6be120ff58729d4020e9b3a08a1108c8dbf0851630b898dc8bf9d30"}
{"level":"debug","msg":"[cni-net] Plugin wcn-net version b9c3a1d-dirty.","time":"2018-05-10T15:54:32Z"}
{"level":"debug","msg":"[net] Network interface: {Index:13 MTU:1500 Name:vEthernet (Ethernet 3) HardwareAddr:00:0d:3a:06:6b:a2 Flags:up|broadcast|multicast} with IP addresses: [fe80::857d:1b6a:9a42:f58/64 10.240.0.4/12]","time":"2018-05-10T15:54:32Z"}
{"level":"debug","msg":"[net] Network interface: {Index:4 MTU:1500 Name:vEthernet (nat) HardwareAddr:00:15:5d:71:de:a1 Flags:up|broadcast|multicast} with IP addresses: [fe80::7574:3878:b12d:80ec/64 172.30.48.1/20]","time":"2018-05-10T15:54:32Z"}
{"level":"debug","msg":"[net] Network interface: {Index:1 MTU:-1 Name:Loopback Pseudo-Interface 1 HardwareAddr: Flags:up|loopback|multicast} with IP addresses: [::1/128 127.0.0.1/8]","time":"2018-05-10T15:54:32Z"}
{"level":"debug","msg":"[cni-net] Plugin started.","time":"2018-05-10T15:54:32Z"}
{"level":"debug","msg":"[cni-net] Processing ADD command with args {ContainerID:8b0938b6c6be120ff58729d4020e9b3a08a1108c8dbf0851630b898dc8bf9d30 Netns:none IfName:eth0 Args:IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=msftdb;K8S_POD_INFRA_CONTAINER_ID=8b0938b6c6be120ff58729d4020e9b3a08a1108c8dbf0851630b898dc8bf9d30 Path:/opt/wincni.exe/bin;c:\\k\\cni}.","time":"2018-05-10T15:54:32Z"}
{"level":"debug","msg":"[cni-net] Read network configuration \u0026{CniVersion:0.2.0 Name:l2bridge Type:wincni.exe Ipam:{Type: Environment:azure AddrSpace: Subnet:\u003cnone\u003e Address: QueryInterval: Routes:[{Dst:{IP:\u003cnil\u003e Mask:\u003cnil\u003e} GW:10.240.0.1}]} DNS:{Nameservers:[10.0.0.10] Domain: Search:[svc.cluster.local] Options:[]} RuntimeConfig:{PortMappings:[]} AdditionalArgs:[{Name:EndpointPolicy Value:[123 34 69 120 99 101 112 116 105 111 110 76 105 115 116 34 58 91 34 49 48 46 50 52 48 46 48 46 48 47 49 50 34 44 34 49 48 46 50 52 48 46 48 46 48 47 49 50 34 93 44 34 84 121 112 101 34 58 34 79 117 116 66 111 117 110 100 78 65 84 34 125]} {Name:EndpointPolicy Value:[123 34 68 101 115 116 105 110 97 116 105 111 110 80 114 101 102 105 120 34 58 34 49 48 46 48 46 48 46 48 47 49 54 34 44 34 78 101 101 100 69 110 99 97 112 34 58 116 114 117 101 44 34 84 121 112 101 34 58 34 82 79 85 84 69 34 125]}]}.","time":"2018-05-10T15:54:32Z"}
panic: runtime error: index out of range
```

```
Invoke-HNSRequest : @{Error=The parameter is incorrect. ; Success=False}
At C:\k\hns.psm1:204 char:16
+ ...      return Invoke-HNSRequest -Method POST -Type networks -Data $Json ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep 
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio 
   n,Invoke-HNSRequest
 
```

Also noticed this popped up when the kubelet tried to start ☝️

**Comment by beaudryj** [comment]
Forgot to show pod logs 
`
~ $ kubectl describe pods msftdb
Name:         msftdb
Namespace:    default
Node:         28006acs000005/10.240.0.4
Start Time:   Thu, 10 May 2018 11:28:35 -0400
Labels:       name=msftdb
Annotations:  <none>
Status:       Pending
IP:
Containers:
  msftdb:
    Container ID:
    Image:          microsoft/mssql-server-windows-express:1709
    Image ID:
    Port:           1433/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fghmv (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  default-token-fghmv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-fghmv
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  beta.kubernetes.io/os=windows
Tolerations:     <none>
Events:
  Type     Reason                  Age                From                     Message
  ----     ------                  ----               ----                     -------
  Normal   Scheduled               7m                 default-scheduler        Successfully assigned msftdb to 28006acs000005
  Normal   SuccessfulMountVolume   7m                 kubelet, 28006acs000005  MountVolume.SetUp succeeded for volume "default-token-fghmv"
  Normal   SandboxChanged          6m (x12 over 7m)   kubelet, 28006acs000005  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  2m (x138 over 7m)  kubelet, 28006acs000005  Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "msftdb_default" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
`

Also did see the pause image is being accessed from the master 
![image](https://user-images.githubusercontent.com/2633564/39880160-e806f128-544a-11e8-8310-5ac783ca79d4.png)

**Comment by kichristensen** [comment]
I got the exact same issue

**Comment by feiskyer** [comment]
Seems this is a Azure CNI plugin setup issue? Could you show the cni configure file? I'm using none network policy, which runs smoothly.

**Comment by BuairtRi** [comment]
I'm having incredible difficulty with CNI issues on my nodes. It seems that everything works fine for a bit, and then all of the sudden, I can't start any pods because of CNI issues.

**Comment by feiskyer** [comment]
> It seems that everything works fine for a bit, and then all of the sudden, I can't start any pods because of CNI issues.

@BuairtRi  Have you done something between? Could you show the cni configure file?

**Comment by ariellapinin** [comment]
+1
I'm experiencing the same behavior: at start everything works and then the internal kubernetes network isn't available from the windows node. any workaround this?

**Comment by feiskyer** [comment]
@ariellapinin Could you elaborate the Kubernetes network issues? Is VM network still working?

**Comment by ariellapinin** [comment]
yes, and when running ipconfig on the container I'm getting this:
```
 ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : web-5cdbc8dc96-sr2lp
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : default.svc.cluster.local

Ethernet adapter vEthernet (954c9721-eth0):

   Connection-specific DNS Suffix  . : default.svc.cluster.local
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #3
   Physical Address. . . . . . . . . : 00-15-5D-5F-F1-F2
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::c194:a091:fb29:3cd3%21(Preferred)
   IPv4 Address. . . . . . . . . . . : 10.240.0.69(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.240.0.0
   Default Gateway . . . . . . . . . : 10.240.0.1
   DNS Servers . . . . . . . . . . . : 10.0.0.10
                                       168.63.129.16
   NetBIOS over Tcpip. . . . . . . . : Disabled
```
this is version from the current master. It seems like the problem isn't related to dns, because when trying to resolve to any kubernetes network ip, I'm getting timeout

**Comment by feiskyer** [comment]
@ariellapinin Could you check whether steps at [here](https://kubernetes.feisky.xyz/en/troubleshooting/windows.html#windows-pod-failed-to-resolve-dns) help for your issue?

**Comment by feiskyer** [comment]
Not meeting this issue for a long time. It should have been resolved.

@beaudryj Feel free to open a new issue if you still have problems with new aks-engine.

/close
