### ISSUE TITLE
ERROR: Parameter 'account_name' must have length less than 24.

### ISSUE THREAD

**Issue by kargakis** [Azure/acs-engine#2924]
```
+ update-ca-trust
+ rpm -i https://packages.microsoft.com/yumrepos/azure-cli/azure-cli-2.0.31-1.el7.x86_64.rpm
warning: /var/tmp/rpm-tmp.lY2vrb: Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
+ set +x
ERROR: Parameter 'account_name' must have length less than 24.
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    result = cmd(params)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 180, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/mgmt/storage/v2017_10_01/operations/storage_accounts_operations.py", line 569, in list_keys
    'accountName': self._serialize.url("account_name", account_name, 'str', max_length=24, min_length=3),
  File "/usr/lib64/az/lib/python2.7/site-packages/msrest/serialization.py", line 488, in url
    data = self.validate(data, name, required=True, **kwargs)
  File "/usr/lib64/az/lib/python2.7/site-packages/msrest/serialization.py", line 568, in validate
    raise ValidationError(key, name, value)
ValidationError: Parameter 'account_name' must have length less than 24.
```
Saw this in https://github.com/Azure/acs-engine/pull/2908. Unclear yet whether it's my PR or something else.

@jim-minter @maxamillion

**Comment by kwoodson** [comment]
@kargakis, Please check the storage account name and verify its length.  There are restrictions to naming schemes.

**Comment by jim-minter** [comment]
```
REGISTRY_STORAGE_AZURE_ACCOUNTNAME=$(az storage account list -g "$resourceGroup" --query "[?ends_with(name, 'registry')].name" -o tsv)
REGISTRY_STORAGE_AZURE_ACCOUNTKEY=$(az storage account keys list -g "$resourceGroup" -n "$REGISTRY_STORAGE_AZURE_ACCOUNTNAME" --query "[?keyName == 'key1'].value" -o tsv)
```

The most plausible explanation I can find is that you deployed to a resource group which had a pre-existing storage account whose name also terminated in 'registry'.
